#!/usr/bin/env bash
trap "kill 0" exit
set -euo pipefail
rm -rf dist
mkdir -p dist
echo "building src folder ..."
./node_modules/.bin/lsc -o ./dist/ -cb src
echo "building cli ..."
echo "#!/usr/bin/env node" > ./dist/cli
cat ./dist/cli.js >> ./dist/cli
chmod 755 ./dist/cli
echo "building pug-cli ..."
echo "#!/usr/bin/env node" > ./dist/pug-cli
cat ./dist/pug-cli.js >> ./dist/pug-cli
chmod 755 ./dist/pug-cli
wait
